# Generated by Django 4.1 on 2023-03-10 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_alter_like_post_alter_like_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='likes',
        ),
    ]
