# Generated by Django 4.1 on 2023-03-12 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0004_post_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='likes',
        ),
    ]
