# Generated by Django 4.1 on 2023-09-20 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0014_comment_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='edited_comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
