# Generated by Django 4.1 on 2023-09-25 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0017_comment_parent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='parent',
            new_name='reply_to',
        ),
    ]
