# Generated by Django 4.1 on 2023-09-25 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0018_rename_parent_comment_reply_to'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-date_posted']},
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='reply_to',
            new_name='parent',
        ),
    ]
