# Generated by Django 4.1 on 2023-09-25 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0019_alter_comment_options_rename_reply_to_comment_parent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={},
        ),
        migrations.RemoveField(
            model_name='comment',
            name='parent',
        ),
    ]
