# Generated by Django 4.1 on 2023-09-28 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0020_alter_comment_options_remove_comment_parent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='post',
            new_name='user_input',
        ),
        migrations.AddField(
            model_name='post',
            name='markdown_content',
            field=models.TextField(default='', editable=False),
            preserve_default=False,
        ),
    ]
