# Generated by Django 4.1 on 2023-09-29 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0021_rename_post_post_user_input_post_markdown_content'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='user_input',
            new_name='post',
        ),
        migrations.RemoveField(
            model_name='post',
            name='markdown_content',
        ),
    ]
